# Generated by Django 3.1.3 on 2020-11-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.TextField(max_length=200)),
                ('nazwisko', models.TextField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Zmiana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ilosc_pracownikow', models.SmallIntegerField()),
                ('czas_pracy', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pora', models.CharField(choices=[('dzien', 'dzien'), ('noc', 'noc')], max_length=5)),
                ('typ', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('data_od', models.DateField(blank=True, null=True)),
                ('data_do', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pracownicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.pracownik')),
                ('zmiany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.zmiana')),
            ],
        ),
    ]
