# Generated by Django 3.1.3 on 2020-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_pracownik_numer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
