# Generated by Django 3.1.3 on 2020-11-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20201123_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmiana',
            name='typ',
            field=models.CharField(choices=[('1', 'wszystkie'), ('2', 'tydzien'), ('3', 'weekend'), ('4', 'daty')], max_length=19),
        ),
    ]
