# Generated by Django 3.1.3 on 2020-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20201123_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nazwa',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
