# Generated by Django 3.1.3 on 2020-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20201123_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='max_ilosc_godzin',
            field=models.SmallIntegerField(default=160),
        ),
    ]
