# Generated by Django 3.1.3 on 2020-11-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_pracownik_max_ilosc_godzin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pracownicy',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='zmiany',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zmiana',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.plan'),
            preserve_default=False,
        ),
    ]
