# Generated by Django 3.1.3 on 2020-11-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20201123_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('ilosc_pracownikow', models.SmallIntegerField()),
                ('czas_pracy', models.DecimalField(decimal_places=1, default=12, max_digits=3)),
                ('pora', models.CharField(choices=[('dzien', 'dzien'), ('noc', 'noc')], max_length=5)),
                ('dzien', models.CharField(choices=[(None, None), (0, 'Poniedzialek'), (1, 'Wtorek'), (2, 'Sroda'), (3, 'Czwartek'), (4, 'Piatek'), (5, 'Sobota'), (6, 'Niedziela'), ('Wszystkie', 'Wszystkie')], max_length=19)),
                ('data_od', models.DateField(blank=True, null=True)),
                ('data_do', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.plan')),
            ],
        ),
        migrations.DeleteModel(
            name='Zmiana',
        ),
    ]
