# Generated by Django 3.1.3 on 2020-11-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_auto_20201125_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regula',
            name='czas_pracy',
        ),
    ]
