# Generated by Django 3.1.3 on 2020-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_remove_regula_czas_pracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regula',
            name='dzien',
            field=models.CharField(choices=[(None, None), ('0', 'Poniedzialek'), ('1', 'Wtorek'), ('2', 'Sroda'), ('3', 'Czwartek'), ('4', 'Piatek'), ('5', 'Sobota'), ('6', 'Niedziela'), ('14', 'Pon-Pt'), ('15', 'Pon-Sb'), ('56', 'Weekend'), ('Wszystkie', 'Wszystkie')], max_length=19),
        ),
    ]
