# Generated by Django 3.1.3 on 2020-11-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_auto_20201125_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='dniowka',
            name='grafik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.grafik'),
        ),
    ]
