# Generated by Django 3.1.3 on 2020-11-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_dniowka_grafik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dniowka',
            new_name='Doba',
        ),
    ]
