# Generated by Django 3.1.3 on 2020-11-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_auto_20201125_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doba',
            name='pracownicy_dzien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracownicy_dzien', to='generator.pracownik'),
        ),
        migrations.AlterField(
            model_name='doba',
            name='pracownicy_noc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracownicy_noc', to='generator.pracownik'),
        ),
    ]
