# Generated by Django 3.1.3 on 2020-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_auto_20201125_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
