# Generated by Django 3.1.3 on 2020-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_grafik_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doba',
            name='pracownicy_dzien',
        ),
        migrations.AddField(
            model_name='doba',
            name='pracownicy_dzien',
            field=models.ManyToManyField(null=True, related_name='pracownicy_dzien', to='generator.Pracownik'),
        ),
        migrations.RemoveField(
            model_name='doba',
            name='pracownicy_noc',
        ),
        migrations.AddField(
            model_name='doba',
            name='pracownicy_noc',
            field=models.ManyToManyField(null=True, related_name='pracownicy_noc', to='generator.Pracownik'),
        ),
    ]
