# Generated by Django 3.1.3 on 2020-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_auto_20201125_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pracownik',
            old_name='max_ilosc_godzin',
            new_name='ilosc_godzin',
        ),
        migrations.AlterField(
            model_name='doba',
            name='pracownicy_dzien',
            field=models.ManyToManyField(related_name='pracownicy_dzien', to='generator.Pracownik'),
        ),
        migrations.AlterField(
            model_name='doba',
            name='pracownicy_noc',
            field=models.ManyToManyField(related_name='pracownicy_noc', to='generator.Pracownik'),
        ),
    ]
