# Generated by Django 3.1.3 on 2020-12-03 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_auto_20201129_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dni_swiateczne',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='regula',
            name='dzien',
            field=models.CharField(choices=[('None', 'None'), ('0', 'Poniedzialek'), ('1', 'Wtorek'), ('2', 'Sroda'), ('3', 'Czwartek'), ('4', 'Piatek'), ('5', 'Sobota'), ('6', 'Niedziela'), ('14', 'Pon-Pt'), ('15', 'Pon-Sb'), ('56', 'Weekend'), ('Wszystkie', 'Wszystkie')], max_length=19),
        ),
    ]
