# Generated by Django 3.1.3 on 2020-12-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_auto_20201203_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='dni_swiateczne',
        ),
        migrations.CreateModel(
            name='Dni_swiateczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('dni_swiateczne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dni_swiateczne', to='generator.plan')),
            ],
        ),
    ]
