# Generated by Django 3.1.3 on 2020-12-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_auto_20201203_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dni_swiateczne',
            options={'verbose_name': 'Dzień świąteczny', 'verbose_name_plural': 'Dni świąteczne'},
        ),
        migrations.AlterModelOptions(
            name='doba',
            options={'verbose_name': 'Doba', 'verbose_name_plural': 'Doby'},
        ),
        migrations.AlterModelOptions(
            name='grafik',
            options={'verbose_name': 'Grafik', 'verbose_name_plural': 'Grafiki'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plany'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='regula',
            options={'verbose_name': 'Reguła', 'verbose_name_plural': 'Reguły'},
        ),
        migrations.CreateModel(
            name='Prosba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien', models.BooleanField()),
                ('noc', models.BooleanField()),
                ('data', models.DateField(blank=True, null=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.pracownik')),
            ],
            options={
                'verbose_name': 'Prośba',
                'verbose_name_plural': 'Prośby',
            },
        ),
    ]
