# Generated by Django 3.1.3 on 2020-12-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_plan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField(blank=True, null=True)),
                ('data_do', models.DateField(blank=True, null=True)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.pracownik')),
            ],
            options={
                'verbose_name': 'Urlop',
                'verbose_name_plural': 'Urlopy',
            },
        ),
    ]
