# Generated by Django 3.1.3 on 2020-12-08 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_urlop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='dni_urlopu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
